# Run CI workflow for Python on Pull Request event and workflow_dispatch
name: CI Python

on:
  pull_request:
    branches:
      - feature*
      - develop
    paths:
      - '*.py'
      - '**/*.py'
  workflow_dispatch:

jobs:
  Pre-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is automatically triggered by a ${{ github.event_name }} event."

  Flake8-Linting:
    runs-on: ubuntu-latest
    needs: [Pre-Deploy]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: 100
          update-pip: true

  Black-Formatting:
    runs-on: ubuntu-latest
    needs: [Pre-Deploy]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Black
        uses: psf/black@stable
        with:
          options: "--check --verbose"

  Python-Code-Scan:
    runs-on: ubuntu-latest
    needs: [Pre-Deploy]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Run Snyk Code Scan
        run: snyk code test --severity-threshold=high # this covers high and critical
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
