# Run CI workflow for Terraform on Pull Request event and workflow_dispatch.
# Take note that the 'cd_tf.yml' workflow execution is dispatched manually.
name: CI Terraform

on:
  #pull_request:
  #  branches:
  #    - develop
  #  paths:
  #    - 'terraform/**
  workflow_dispatch:
    inputs:
      confirm:
        description: "Do you really want to proceed? (y/n)"
        required: true
        default: 'n'
        type: choice
        options:
          - 'y'
          - 'n'  

jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is automatically triggered by a ${{ github.event_name }} event."

  terraform-ci:
    name: Terraform CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # To check that this preparation steps in the job workflow are running
      # properly up to now

      - name: Check the tf code for programmatic and stylistic errors
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: latest

      - name: Show the version installed
        run: tflint --version

      - name: Init TFLinit
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      - name: Terraform Init
        run: terraform init

      - name: Clean up the spacing format of the tf code
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate -no-color
