# This workflow will build and push a new container image to Amazon ECR:
#  - Previous docker push step: docker push public.ecr.aws/sctp-sandbox/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}.${{ github.run_number }}

name: Build and push to Amazon ECR

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Tag for the Container image"
        required: true
        default: "v1.0"

env:
  AWS_REGION: us-east-1
  APP_NAME: predict-buy-app

jobs:
  Deploy:
    name: Register Container Image
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # ECR Private Repo
      #- name: Login to Amazon ECR
      #  id: login-ecr
      #  uses: aws-actions/amazon-ecr-login@v1
      # ECR Public Repo
      - name: Login to ECR
        run: aws ecr-public get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin public.ecr.aws/sctp-sandbox

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          #IMAGE_TAG: ${{ github.sha }} -> Git commit hash value if workflow trigger is non workflow dispatch
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
        run: |
          docker build -t ${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}.${{ github.run_number }} -t ${{ env.APP_NAME }}:latest .
          docker tag ${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}.${{ github.run_number }} public.ecr.aws/sctp-sandbox/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}.${{ github.run_number }}
          docker tag ${{ env.APP_NAME }}:latest public.ecr.aws/sctp-sandbox/${{ env.APP_NAME }}:latest
          docker push public.ecr.aws/sctp-sandbox/${{ env.APP_NAME }} --all-tags
          echo "IMAGE_NAME=${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Display Image Name
        run: echo "The built image name is ${{ steps.build-image.outputs.IMAGE_NAME }}"
