name: Snyk Docker Image Scan

on:
  #pull_request:
  #  branches: [ "main" ]
  #  paths:
  #      - '*.py'
  #      - '**/*.py'
  workflow_dispatch:

jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is automatically triggered by a ${{ github.event_name }} event."
      
  docker-image-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Run Snyk Docker Image Scan And Check Snyk Scan Results
      id: scan-docker-image
      env:
        ECR_REPO_REG: ${{ steps.login-ecr.outputs.registry }}
        APP_REPO_NAME: ${{ vars.NONPROD_IMAGE_NAME }}
        SYNK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        snyk container test ${{ env.ECR_REPO_REG }}/${{ env.APP_REPO_NAME }}:latest -file=dockerfile --severity-threshold=high 
        echo "REG_IMAGE_NAME=${{ env.ECR_REPO_REG }}/${{ env.APP_REPO_NAME }}:latest" >> $GITHUB_OUTPUT

    - name: Display Image Name
      run: echo "The built image name is ${{ steps.scan-docker-image.outputs.REG_IMAGE_NAME }}"
