# Run Python code linter using Flake8
#   - check tox.ini config for the flake8 init parameters
name: Flake8 Lint

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  workflow_dispatch:

jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is automatically triggered by a ${{ github.event_name }} event."
      
  flake8-linting:
    name: Flake8 linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: 100
          update-pip: true
