# Run Python code linter using Flake8
name: Flake8 Lint

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  workflow_dispatch:

jobs:
  flake8-linting:
    name: Flake8 linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "80"
          update-pip: true
