# Retrain ML Model whenever there is data changes only,
# or there is both data and source code changes.
name: Retrain ML Model

on:
  schedule:
    - cron: "0 0 * * 1" # Runs weekly every Monday at midnight
  #workflow_dispatch:

env:
  ML_ARTEFACTS_S3: s3://ce7-lcchua-project/ml_artefacts/
  ML_DATASETS_S3: s3://ce7-lcchua-project/ml_datasets/
  VER_TAG: ${{ github.sha }}

jobs:
  Retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Specify the required Python version

      - name: Create and update Python ML venv
        run: | # inclusive of dvc[s3] install
          python3 -m venv venv
          echo "PATH=$(pwd)/venv/bin:$PATH" >> $GITHUB_ENV

      - name: Install packages and dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      # Model training on the basis of data changes only, or both data and .py source changes
      #    ??? To add conditional check for no data and/or .py source changes then do not execute workflow ???
      - name: Pull datasets from S3
        run: aws s3 cp ${{ env.ML_DATASETS_S3 }} data/ --recursive

      - name: Train the prediction model
        run: make run

      - name: Test the trained model
        run: make test

      - name: Version ML and Git artefacts
        run: |
          dvc add data/train.csv
          dvc add data/test.csv
          git add data/train.csv.dvc data/.gitignore
          git add data/test.csv.dvc data/.gitignore
          git commit -m "add training and testing data ${{ env.VER_TAG }}"
          dvc add models/model.pkl
          git add models/model.pkl.dvc models/.gitignore
          git commit -m "add trained model ${{ env.VER_TAG }}"
          dvc remote add -d remote ${{ env.ML_ARTEFACTS_S3 }}
          dvc push
          git push origin main
          git add .

      - name: Commit & push Git changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up the training environment
        run: make clean
