# Retraining Pipeline with previous and new incremental datasets,
# there is no new data attributes or code refactor.
name: Retrain ML Model

on:
  schedule:
    - cron: "0 0 * * 1" # Runs weekly every Monday at midnight
  #workflow_dispatch:

env:
  AWS_S3_STORAGE: s3://ce7-lcchua-project/ml_artefacts/
  VER_TAG: ${{ github.sha }} -> Git commit hash value if not workflow dispatch

jobs:
  Retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Specify the required Python version

      - name: Create and update Python ML venv
        run: | # inclusive of dvc[s3] install
          python3 -m venv venv
          echo "PATH=$(pwd)/venv/bin:$PATH" >> $GITHUB_ENV 
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pull from DVC # to check if there are changes to the dataset and run the remaining steps only if so
        run: dvc pull data/train.csv data/test.csv

      - name: Train the prediction model
        run: make run

      - name: Test the trained model
        run: make test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Version ML and Git artefacts
        run: |
          dvc add data/train.csv
          dvc add data/test.csv
          git add data/train.csv.dvc data/.gitignore
          git add data/test.csv.dvc data/.gitignore
          git commit -m "add training and testing data ${{ env.VER_TAG }}"
          dvc add models/model.pkl
          git add models/model.pkl.dvc models/.gitignore
          git commit -m "add trained model ${{ env.VER_TAG }}"
          dvc remote add -d remote ${{ env.AWS_S3_STORAGE }}
          dvc push
          git push origin main
          git add .

      - name: Commit & push Git changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up the training environment
        run: make clean
