name: Snyk Package Vulnerabilities Scan

on:
  #pull_request:
  #  branches: [ "main" ]
  #  paths:
  #      - '*.py'
  #      - '**/*.py'
  workflow_dispatch:

jobs:
  code-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Run Snyk Code Scan And Check Snyk Scan Results
        run: snyk code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  
  terraform-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Run Snyk Terraform Scan And Check Snyk Scan Results
        run: snyk iac test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
