name: Checkov Terraform Scan

on:
  #pull_request:
  #  branches: [ "main" ]
  #  paths:
  #    - 'terraform/*'
  workflow_dispatch:

jobs:
  Checkov:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        framework: terraform
        # This will add both a CLI output to the console and create a results.sarif file
        output_format: cli,sarif
        output_file_path: console,checkov.sarif
        skip_check: CKV_AWS_56,CKV_AWS_55,CKV_AWS_54,CKV_AWS_53,CKV2_AWS_62,CKV2_AWS_65,CKV_AWS_144,CKV2_AWS_61,CKV2_AWS_6
        quiet: true # display only failed checks

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
        
      # Results are generated only on a success or failure
      # this is required since GitHub by default won't run the next step
      # when the previous one has failed. Security checks that do not pass will 'fail'.
      # An alternative is to add `continue-on-error: true` to the previous step
      # Or 'soft_fail: true' to checkov.
      if: success() || failure()
      with:
        sarif_file: checkov.sarif

